version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Bogota"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps(composer)"
    groups:
      composer-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "America/Bogota"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps(npm)"
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
